### ISSUE TITLE
Request body is always empty

### ISSUE THREAD

**Issue by kidonng** [vercel-community/deno#104]
I was testing a project using Webhook and everything looks just fine, including the request headers (like `content-length` or `content-type`), but I always got a empty request body, thus failed my purpose.

Reproduced with 1.14.0 and the lastest available 1.18.0 version.

**Comment by TooTallNate** [comment]
Ya you are right. That's not good. Do you see anything incorrect with the approach here?

```typescript 
// Legacy `std` HTTP server interface
const input = new Deno.Buffer(base64.decode(data.body || ''));

// req.conn
this.r = new BufReader(input, input.length);
```

**Comment by TooTallNate** [comment]
It's probably also time to set up [Vercel Checks](https://vercel.com/docs/concepts/deployments/checks) to ensure that this doesn't regress again in the future.

**Comment by kidonng** [comment]
I did some attempt to fix it but no luck, will try to investigate again later.

**Comment by nestarz** [comment]
It's still an issue with the latest runtime for me too.
